from typing import Any, Mapping, Sequence, Hashable

def gloom(obj: Sequence | Mapping | object | None, spec: tuple[Hashable, ...] | str, default=None) -> Any: ...
def assign(obj: Sequence | Mapping | object | None, path: tuple[Hashable, ...] | str, value: Any) -> Any: ...
