from typing import Any, Mapping, Sequence, Hashable

# def gloom(target: Sequence | Mapping | object | None, spec: str, default=None): ...
# def gloom_path(target: Sequence | Mapping | object | None, spec: tuple[Hashable, ...], default=None): ...
def gloom_compat(obj: Sequence | Mapping | object | None, spec: tuple[Hashable, ...] | str, default=None) -> Any: ...

# def gloom_assign(obj: Sequence | Mapping | object | None, path: str, value: Any) -> Any: ...
# def gloom_assign_path(obj: Sequence | Mapping | object | None, path: tuple[Hashable, ...], value: Any) -> Any: ...
def assign(obj: Sequence | Mapping | object | None, path: tuple[Hashable, ...] | str, value: Any) -> Any: ...
