from typing import Any, Mapping, Sequence, Hashable

def gloom_rusty(target: Sequence | Mapping | object | None, spec: str, default=None): ...
def gloom_path(target: Sequence | Mapping | object | None, spec: tuple[Hashable, ...], default=None): ...
def gloom_assign(obj: Sequence | Mapping | object | None, path: str, value: Any) -> Any: ...
